# 一.ndarray
## 1.ndarray的特性
### 多维性

In [2]:
import numpy as np
from certifi import where

In [4]:
arr=np.array(5) #只有一个数字0维度
print(arr)
print("arr的维度：",np.ndim) #ndim是维度

5
arr的维度： <function ndim at 0x1133382c0>


In [5]:
arr=np.array([1,2,3])
print(arr)
print("the dimension of arr is ",arr.ndim)

[1 2 3]
the dimension of arr is  1


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("the dimension of arr is ",arr.ndim)

[[1 2 3]
 [4 5 6]]
the dimension of arr is  2


### 同质性

In [7]:
arr = np.array([1,'hello']) #虽然数组创建成功， 不同的数据类型会被创建成相同的数据类型
print(arr)

['1' 'hello']


In [8]:
arr = np.array([1,1.2]) #虽然数组创建成功， 不同的数据类型会被创建成相同的数据类型
print(arr)

[1.  1.2]


## 2.ndarray的属性

In [21]:
arr=np.array(1)
print(arr)
print("数组的形状:",arr.shape)
print("数组的维度",arr.ndim)
print("数组的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置",arr.T)

1
数组的形状: ()
数组的维度 0
数组的个数 1
元素的数据类型 int64
元素的转置 1


In [22]:
arr=np.array([1,2,3])
print(arr)
print("数组的形状:",arr.shape)
print("数组的维度",arr.ndim)
print("数组的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置",arr.T)

[1 2 3]
数组的形状: (3,)
数组的维度 1
数组的个数 3
元素的数据类型 int64
元素的转置 [1 2 3]


In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("数组的形状:",arr.shape)
print("数组的维度",arr.ndim)
print("数组的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置",arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状: (2, 3)
数组的维度 2
数组的个数 6
元素的数据类型 int64
元素的转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [30]:
#基础语法
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
list1=[1,2,3]
print(arr.ndim)
print(arr)

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
#copy
arr1=np.copy(arr)# 深拷贝
print(arr1)
arr1[1][1]=2
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 2 6]
 [7 8 9]]


In [33]:
# 预定义形状（全0， 全1）

#全0
arr=np.zeros((2,3),dtype=int)
print(arr)


[[0 0 0]
 [0 0 0]]


In [35]:
# 全1
arr=np.ones((5,8),dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [36]:
# 创建一个空数组
arr=np.empty((5,8),dtype=int)
print(arr)

[[4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408]]


In [37]:
# 创建自定义
arr=np.full((3,4),5)
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [39]:
# 得到形状一致的矩阵
arr2=np.zeros_like(arr)
print(arr2)
arr2=np.empty_like(arr)
print(arr2)
arr2=np.ones_like(arr)
print(arr2)
arr2=np.full_like(arr,2025)
print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [43]:
# 等差数列 2 4 6 8 10
arr=np.arange(2,11,2) #末尾不包含
print(arr)


[ 2  4  6  8 10]


In [45]:
# 等间隔的序列
arr=np.linspace(0,10,5) #包含末尾
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [47]:
arr=np.linspace(0,100,5,dtype=int)
print(arr)

[  0  25  50  75 100]


In [50]:
arr=np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]


In [52]:
# 对数间隔数列
arr=np.logspace(0,4,3,base=2)
print(arr)

[ 1.  4. 16.]


In [2]:
import numpy as np
arr=np.linspace(0,4,3,dtype=int)
print(arr)

[0 2 4]


## 5.索引与切片

In [3]:
# 一维数组
arr=np.random.randint(1,100,20)
print(arr)

[67 63 39  5  9 67 70 74 57 41 91  5 37 24 92 73 17 97 54 87]


In [4]:
print(arr[0])

67


In [9]:
print(arr[:])
print(arr[2:10:2])
print(arr[slice(2,10,2)])
print(arr[(arr>10) & (arr<20)])

[67 63 39  5  9 67 70 74 57 41 91  5 37 24 92 73 17 97 54 87]
[39  9 70 57]
[39  9 70 57]
[17]


In [10]:
#二维数组

arr=np.random.randint(1,100,(4,8))
print(arr)

[[79 98 86 80  9 85 74 43]
 [83 86  4 65 79 78 19 85]
 [12 44 19 29 53  8 88 12]
 [53 44 93 92 29 83 22  8]]


In [12]:
print(arr[2,1])

44


In [14]:
print(arr[1,0:3])

[83 86  4]


In [16]:
print(arr[2][arr[2]>50])

[53 88]


In [17]:
print(arr[:,2][arr[:,2]>50])

[86 93]


## 6.ndarray的运算

In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [20]:
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [21]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [22]:
print(a+3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
#广播机制
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [24]:
# 矩阵的运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a@b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 2.3 numpy中常用的函数


In [26]:
# 计算平方根
print(np.sqrt(9))

3.0


In [27]:
print(np.sqrt([1,4,9]))

[1. 2. 3.]


In [29]:
# 计算指数 默认以e为底
print(np.exp(1))

7.38905609893065


In [31]:
# 计算自然对数 lnx
print(np.log(np.exp(1)))

1.0


In [33]:
# 计算正弦余弦
print(np.sin(np.pi/2))


1.0


In [34]:
arr=np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [35]:
# 计算a的b次幂
print(np.power(arr,2))

[1 1 4 9]


In [36]:
# 四舍五入
print(np.round([3.2,4.5,8.1,9.6]))

[ 3.  4.  8. 10.]


In [37]:
# 向上取整， 向下取整
arr=np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [38]:
# 检测缺失值
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

## 统计函数

In [39]:
arr = np.random.randint(1,20,8)
print(arr)

[ 8  2  4 16 15 19 15  8]


In [40]:
#求和
print(np.sum(arr))

87


In [42]:
# 计算平均值
print(np.mean(arr))

10.875


In [44]:
print(np.median(arr))

11.5


In [45]:
# 计算标准差和方差
print(np.var([1,2,3]))
print(np.std([1,2,3]))


0.6666666666666666
0.816496580927726


In [47]:
# 最大值最小值
print(np.max(arr),np.argmin(arr))
print(np.min(arr),np.argmax(arr))

19 1
2 5


In [48]:
# 分位数
print(np.percentile(arr,20))

5.6000000000000005


In [49]:
arr=np.array([1,2,3])
print(np.sum(arr))

6


## 比较函数

In [52]:
# 是否大于

print(np.greater([3,4,5,6,7],4))

#是否小于
print(np.less([3,4,5,6,7],4))

#是否等于
print(np.equal([3,4,5,6,7],[3,4,5,6,7]))
print(np.equal([1,2,3],2))


[False False  True  True  True]
[ True False False False False]
[ True  True  True  True  True]
[False  True False]


In [53]:

print(np.logical_and([1,0],[1,1]))
print(np.logical_or([1,0],[1,1]))
print(np.logical_xor([1,0],[1,1]))
print(np.logical_not([1,0,0]))

[ True False]
[ True  True]
[False  True]
[False  True  True]


In [54]:
# 检测是否有一个为true
print(np.any([0,0,0,0,0]))
# 检测是否全为true
print(np.all([1,0,0]))

False
False


In [56]:
# 自定义条件
arr=np.array([[1,2,3,4,5]])
print(np.where(arr>3,arr,0)) #where(条件，满足是什么，不满足设为什么)

[[0 0 0 4 5]]


In [59]:
arr=np.random.randint(40,100,20)

In [60]:
print(arr)
print(np.where(arr < 60,'不及格', np.where(arr < 80,'良',np.where(arr<90,'不错','优秀'))))


[56 48 99 50 46 61 66 80 66 49 59 54 59 65 88 86 87 83 63 81]
['不及格' '不及格' '优秀' '不及格' '不及格' '良' '良' '不错' '良' '不及格' '不及格' '不及格' '不及格' '良'
 '不错' '不错' '不错' '不错' '良' '不错']


In [62]:
print(np.select(
    [arr<60,(60<=arr) & (arr<=79),arr>=80],
    ['不及格','良','优秀'],
    default='null'))

['不及格' '不及格' '优秀' '不及格' '不及格' '良' '良' '优秀' '良' '不及格' '不及格' '不及格' '不及格' '良'
 '优秀' '优秀' '优秀' '优秀' '良' '优秀']


In [63]:
arr = np.random.randint(1,100,20)
print(arr)

[86  4 20 58 77 42 83 80 35 15 90 91 59 45 24 82 94 37 77 77]


In [67]:
print(np.sort(arr))
print(np.argsort(arr))
arr.sort()
print(arr)

[ 4 15 20 24 35 37 42 45 58 59 77 77 77 80 82 83 86 90 91 94]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4 15 20 24 35 37 42 45 58 59 77 77 77 80 82 83 86 90 91 94]


In [68]:
#去重函数
print(np.unique(arr))

[ 4 15 20 24 35 37 42 45 58 59 77 80 82 83 86 90 91 94]


In [69]:
#数组拼接
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate([arr1,arr2]))

[5 7 9]
[1 2 3 4 5 6]


In [71]:
# 数组的分割
print(np.split(arr,2))
print(np.split(arr,[6,12,18]))

[array([ 4, 15, 20, 24, 35, 37, 42, 45, 58, 59]), array([77, 77, 77, 80, 82, 83, 86, 90, 91, 94])]
[array([ 4, 15, 20, 24, 35, 37]), array([42, 45, 58, 59, 77, 77]), array([77, 80, 82, 83, 86, 90]), array([91, 94])]


In [72]:
print(np.reshape(arr,(5,4)))

[[ 4 15 20 24]
 [35 37 42 45]
 [58 59 77 77]
 [77 80 82 83]
 [86 90 91 94]]
